
services:
  db:
    image: postgres:latest
    container_name: server-db
    environment:
      POSTGRES_USER: ayman
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: library_db
    ports:
      - "5433:5432"
    networks:
      - pgnetwork
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayman -d library_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: server-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pgnetwork
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:

networks:
  pgnetwork:
    driver: bridge